### ISSUE TITLE
There was an error in evaluating the Pre-request Script:Error: sandbox: execution interrupted, bridge disconnecting.

### ISSUE THREAD

**Issue by nanduri1805** [postman-solutions-eng/postman-contract-test-generator#8]
When I am trying to execute the build schema test am seeing "There was an error in evaluating the Pre-request Script:Error: sandbox: execution interrupted, bridge disconnecting." error could anyone of you help me with this?

Also, I need to validate the schema with the collections and how to map these with the generated Tests.

I need to execute the collection > validate against OAS[Open API specification]
Automate the process.
Appreciate any inputs @jordanwalsh23 

![image](https://github.com/postman-solutions-eng/postman-contract-test-generator/assets/78470863/2dfde4e2-281d-44dc-9d6f-aded9ab402d0)

**Comment by jordanwalsh23** [comment]
Hi @nanduri1805 - I believe this is because the execution of one or more of your endpoints is taking more than 30s to respond. 

See: https://community.postman.com/t/tests-script-running-error-sandbox-execution-interrupted-bridge-disconnecting/5800

At the moment the API calls to your services from the contract test generator are not asynchronous. They are synchronous. So if your endpoints are taking a long time to respond Postman will actively kill the connection resulting in this error.

Can you please take a moment to ensure your endpoints are responding in a reasonable time and re-run to see if this helps.

**Comment by nanduri1805** [comment]
My end points requires Bearer Token and baseURL to execute. where can i provide these values inorder to generate Build Schema Test? I have provided these under ContractGenerator Collection > Autorization and variables is this the right way?
![image](https://github.com/postman-solutions-eng/postman-contract-test-generator/assets/78470863/a3fb0d7e-9d13-48b1-9e6a-4a3ee36fce19)
![image](https://github.com/postman-solutions-eng/postman-contract-test-generator/assets/78470863/e91d2821-a548-470e-bd50-43cad0eb26cd)

**Comment by jordanwalsh23** [comment]
@nanduri1805 it looks like your bearer token is in the right place, however your Base_URL should be in your forked environment file in the `env-Server` parameter.

Try putting it there and see if that works.
